[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "existential-crisis"
version = "0.1.2"
authors = [
  { name = "Skefie", email = "skefie@void-labs.net" },
]
description = "A quick diagnostic CLI for capturing and releasing existential dread."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://void-labs.net"

[project.scripts]
EC = "existential_crisis.main:main"
existential-crisis = "existential_crisis.main:main"
